### ISSUE TITLE
Sample App crash when changed network connection status, from on to offline.

### ISSUE THREAD

**Issue by baksosapi** [OpenSRP/opensrp-client-growth-monitoring#19]
App crash, when network connection unavailable
```
02-01 13:59:13.934 28562-28562/org.smartregister.growthmonitoring.sample D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 48 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
02-01 13:59:13.954 28562-28562/org.smartregister.growthmonitoring.sample I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2784651 time:22342902
02-01 13:59:15.374 28562-28562/org.smartregister.growthmonitoring.sample D/ViewRootImpl: ViewPostImeInputStage processPointer 0
02-01 13:59:15.554 28562-28562/org.smartregister.growthmonitoring.sample D/ViewRootImpl: ViewPostImeInputStage processPointer 1
02-01 13:59:19.464 28562-28562/org.smartregister.growthmonitoring.sample I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2784651 time:22348412
02-01 13:59:33.514 28562-28562/org.smartregister.growthmonitoring.sample I/DRISHTI: Connectivity change receiver triggered.
02-01 13:59:33.514 28562-28562/org.smartregister.growthmonitoring.sample I/DRISHTI: Device got connected to network. Trying to start Dristhi Sync scheduler.
02-01 13:59:46.204 28562-28562/org.smartregister.growthmonitoring.sample I/DRISHTI: Connectivity change receiver triggered.
02-01 13:59:46.204 28562-28562/org.smartregister.growthmonitoring.sample I/DRISHTI: Device got disconnected from network. Stopping Dristhi Sync scheduler.
02-01 13:59:46.204 28562-28562/org.smartregister.growthmonitoring.sample D/AndroidRuntime: Shutting down VM
02-01 13:59:46.204 28562-28562/org.smartregister.growthmonitoring.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                           Process: org.smartregister.growthmonitoring.sample, PID: 28562
                                                                                           java.lang.RuntimeException: Unable to start receiver org.smartregister.view.receiver.ConnectivityChangeReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
                                                                                               at android.app.ActivityThread.handleReceiver(ActivityThread.java:3644)
                                                                                               at android.app.ActivityThread.access$2000(ActivityThread.java:223)
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                               at android.os.Looper.loop(Looper.java:158)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:7231)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
                                                                                               at android.content.ComponentName.<init>(ComponentName.java:129)
                                                                                               at android.content.Intent.<init>(Intent.java:5295)
                                                                                               at org.smartregister.sync.DrishtiSyncScheduler.stop(DrishtiSyncScheduler.java:69)
                                                                                               at org.smartregister.view.receiver.ConnectivityChangeReceiver.onReceive(ConnectivityChangeReceiver.java:20)
                                                                                               at android.app.ActivityThread.handleReceiver(ActivityThread.java:3637)
                                                                                               at android.app.ActivityThread.access$2000(ActivityThread.java:223) 
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                               at android.os.Looper.loop(Looper.java:158) 
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:7231) 
                                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

**Comment by keymane** [comment]
This has been fixed in core version 1.20-SNAPSHOT
